### ISSUE TITLE
No module named 'midas'

### ISSUE THREAD

**Issue by MasonMenzies** [MohamadZeina/Disco_Diffusion_Local#10]
From 1.4 Define Midas functions 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [4], in <cell line: 4>()
      1 #@title ### 1.4 Define Midas functions
----> 4 from midas.dpt_depth import DPTDepthModel
      5 from midas.midas_net import MidasNet
      6 from midas.midas_net_custom import MidasNet_small

ModuleNotFoundError: No module named 'midas'

No clue what I did wrong. running Win11, 21h2.

Installed everything as directed. Perhaps I goofed somewhere along the way.

**Comment by MohamadZeina** [comment]
The cell above this should install Midas for you, probably something is going wrong there. Look for any errors in this previous cell.

Are you running this in Ubuntu WSL, or trying to run it natively in Windows?

**Comment by Vikas-singh-0** [comment]
I also get same error I am using in windows with google colab using local runtime.
