### ISSUE TITLE
ModuleNotFoundError:No module named 'py3d_tools'

### ISSUE THREAD

**Issue by MrDeemoZe** [MohamadZeina/Disco_Diffusion_Local#11]
ModuleNotFoundError                       Traceback (most recent call last)
Input In [8], in <cell line: 6>()
      1 #@title 1.5 Define necessary functions
      2 
      3 # https://gist.github.com/adefossez/0646dbe9ed4005480a2407c62aac8869
      5 import pytorch3d.transforms as p3dT
----> 6 import disco_xform_utils as dxf
      8 def interp(t):
      9     return 3 * t**2 - 2 * t ** 3

File ~/Project/disco_xform_utils.py:2, in <module>
      1 import torch, torchvision
----> 2 import py3d_tools as p3d
      3 import midas_utils
      4 from PIL import Image

ModuleNotFoundError: No module named 'py3d_tools'

**Comment by MohamadZeina** [comment]
One of the cells above this should install py3d for you, probably something is going wrong there. Look for any errors in this previous cell.

Are you running this in Ubuntu WSL, or trying to run it natively in Windows?

**Comment by MrDeemoZe** [comment]
I solved this problem by changing "import pytorch3d.transforms as p3dT" to "import py3d_tools as p3d" before step 1.5.
I'm currently running this in Ubuntu18.04 WSL

**Comment by MrDeemoZe** [comment]
well I also tried using the official file in [Disco diffusion](https://github.com/alembics/disco-diffusion,) and resulting in OOM error and exit WSL2. So I think probably using the WSL2 isn't the best choice. Is it possible to run it natively in windows?
Here is the GUI I'm currently using [simple GUI for DD](https://github.com/zhaoyun0071/Disco-Diffusion-Local)

**Comment by naderzr** [comment]
...No module named 'py3d_tools'
I'm having the same issue, it was caused by an error found while installing Pytorch3d in step 1.3

Looking in links: https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu111_pyt1100/download.html
ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)
ERROR: No matching distribution found for pytorch3d

**Comment by MohamadZeina** [comment]
Most of the issues installing PyTorch 3D come from incompatible PyTorch and cuda versions - the versions in the readme should work. That said, the latest notebook 5.2 should have fixed this by only downloading and installing the required code from PyTorch 3D, not the whole thing.
