### ISSUE TITLE
Image.LANCZOS  depreciation & Missing regex package

### ISSUE THREAD

**Issue by andrewmarconi** [MohamadZeina/Disco_Diffusion_Local#12]
## Depreciation Notice

When running `Disco_Diffusion_v5_2_[w_VR_Mode].ipynb` I received depreciation notifications during the diffuse step:

```python
/tmp/ipykernel_11431/XXXXXXXXX.py:513: DeprecationWarning: 
LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  init = init.resize((args.side_x, args.side_y), Image.LANCZOS)
```

## Missing Package

When I followed the README.md file, I found that I was missing the ```regex``` package. It was easily solved with ```conda install regex```, but I'd suggest modifying the instructions to include it:

>  Now install some other dependencies:
> 
> ````python
>   conda install jupyter pandas requests matplotlib regex
>   conda install opencv -c conda-forge
>  ````

Amazing job with this repo... it's the first time I've been able to successfully run DD locally on Windows.... so thanks very much for that!

**Comment by MohamadZeina** [comment]
You're welcome - glad you're getting good use out of it :)

Weird that you had to install regex, it should be in the python standard library. Glad you fixed it anyway

**Comment by azumukupoe** [comment]
I had the same problem...
