### ISSUE TITLE
Ubuntu turns black after running 'jupyter notebook'

### ISSUE THREAD

**Issue by cliu1105** [MohamadZeina/Disco_Diffusion_Local#14]
Hi my Ubuntu turns black except for a cursor after running 'jupyter notebook' command. Before it turns black I saw 'not a try' or something flashed away-I managed to get a screenshot and got the url but it was not valid. The browser shows "localhost refused connection". Any idea about what to do?

**Comment by cliu1105** [comment]
Problem solved (maybe). It still turns black super quickly but the URL works anyway even though I didn't change anything.

**Comment by MohamadZeina** [comment]
Cool, thanks for updating this

**Comment by Lordan2000** [comment]
I found the solution. Apparently I was using a version of Ubuntu that is just called "Ubuntu", which I downloaded from within PowerShell by typing "wsl --list --online" to look up a list of available distros (It was the first option). Simply by switching to Ubuntu 22.04 LTS from the Microsoft Store, and reinstalling all needed components in this newer version of Ubuntu, everything worked just fine
