### ISSUE TITLE
Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by TotallyNotChina** [MohamadZeina/Disco_Diffusion_Local#18]
![168454448-1517a0c4-edef-48de-a217-2d751c40a4f6](https://user-images.githubusercontent.com/24442051/169615710-b54c7da1-390f-4435-a24c-f188a2b528b6.png)

I'm running a simple prompt and ViTB32 as true because otherwise I get a CUDA error or my kernel dies 
Settings 
ViTB32 = True #@param{type:"boolean"}
ViTB16 = False #@param{type:"boolean"}
ViTL14 = False #@param{type:"boolean"} # Default False
RN101 = False #@param{type:"boolean"} # Default False
RN50 = False #@param{type:"boolean"} # Default True
RN50x4 = False #@param{type:"boolean"} # Default False
RN50x16 = False #@param{type:"boolean"}
RN50x64 = False #@param{type:"boolean"}
SLIPB16 = False # param{type:"boolean"} # Default False. Looks broken, likely related to commented import of SLIP_VITB16
SLIPL16 = False # param{type:"boolean"}

**Comment by TotallyNotChina** [comment]
Also get this error "CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 7.31 GiB already allocated; 0 bytes free; 7.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

**Comment by MohamadZeina** [comment]
Sounds like 2 separate issues. Failed to find cuDNN algorithm is probably an error installing cuDNN - try downloading and installing again. CUDA out of memory is self explanatory - it’s trying to use too much video RAM. 8GB VRAM might not be enough, but you can increase your chances by reducing the number of models and reducing resolution
