### ISSUE TITLE
Cant run Jupyter Notebook

### ISSUE THREAD

**Issue by kajukabla** [MohamadZeina/Disco_Diffusion_Local#19]
Im at the end of Step 5. But when I try to run jupyter notebook it prompts me to install jupyter-core but it doesnt seem to work. 

![image](https://user-images.githubusercontent.com/106099463/169857228-04663d03-0694-45f0-8e63-14cddaff5c61.png)

**Comment by kajukabla** [comment]
OK I fixed this by installing Jupyter in Ubuntu. Could maybe add this step to your instructions for folks who havent installed Jupyter before. 
However now I am seeing Permission Denied messages in Ubuntu when I try to run the cells in browser. 

![image](https://user-images.githubusercontent.com/106099463/169883841-aaea3da2-bcc9-4d32-a0c2-c52ae077809f.png)

**Comment by Kallamamran** [comment]
Getting the same error:

![image](https://user-images.githubusercontent.com/25354644/184713989-ec8c47c2-633d-41c0-837a-b36fe5dfcf2a.png)

**Comment by juanpflores** [comment]
Try running Ubuntu with admin permissions to get it to work. I would recommend after step 5 restart ubuntu otherwise, you'll work in sensitive folders that might also cause this error

**Comment by MohamadZeina** [comment]
The instructions already include installing jupyter in ubuntu, this is done when you do

`conda install jupyter pandas requests matplotlib`

Please try recommendation by @juanpflores and see this previous similar issue, and open a new one if not solved: https://github.com/MohamadZeina/Disco_Diffusion_Local/issues/9
