### ISSUE TITLE
Cannot download secondary_model_imagenet_2.pth - file doesn't exist anymore

### ISSUE THREAD

**Issue by nielsfechtel** [MohamadZeina/Disco_Diffusion_Local#20]
Hi, under the step 2. Diffusion and CLIP model settings, the notebook tries to download the file secondary_model_imagenet_2.pth, as I understand it. This fails with a 404. Opening the download-url https://v-diffusion.s3.us-west-2.amazonaws.com/secondary_model_imagenet_2.pth in a browser, AWS reports that the bucket "v-diffusion" no longer exists: 
![image](https://user-images.githubusercontent.com/85522909/170464518-c7ae428d-e7c6-4b0d-a6bc-b190ffb1daa0.png)

In the notebook, the error-message is
```
--2022-05-26 11:47:08--  https://v-diffusion.s3.us-west-2.amazonaws.com/512x512_diffusion_uncond_finetune_008100.pt
Resolving v-diffusion.s3.us-west-2.amazonaws.com (v-diffusion.s3.us-west-2.amazonaws.com)... 52.218.229.9
Connecting to v-diffusion.s3.us-west-2.amazonaws.com (v-diffusion.s3.us-west-2.amazonaws.com)|52.218.229.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-05-26 11:47:09 ERROR 404: Not Found.

--2022-05-26 11:47:09--  https://v-diffusion.s3.us-west-2.amazonaws.com/secondary_model_imagenet_2.pth
``` 

```
Resolving v-diffusion.s3.us-west-2.amazonaws.com (v-diffusion.s3.us-west-2.amazonaws.com)... 52.218.229.9
Connecting to v-diffusion.s3.us-west-2.amazonaws.com (v-diffusion.s3.us-west-2.amazonaws.com)|52.218.229.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-05-26 11:47:10 ERROR 404: Not Found.
```

**Comment by pudumagico** [comment]
same here

**Comment by KeitoTakaishi** [comment]
I cloud get model by executing this [colab](https://colab.research.google.com/github/alembics/disco-diffusion/blob/main/Disco_Diffusion.ipynb) code.

**Comment by rembo613** [comment]
> Thank you Keito, this worked! I'm new to this and wasn't sure where else I could get them. I downloaded the model-files from the URLs in the colab you linked. I'm new to this and wasn't sure where else I could get them. The notebook is now successfully generating images!

Do you mind explaining how you did this please within ubuntu from the colab URLs?
