### ISSUE TITLE
System cannot find nbserver-318-open.html when running jupyter notebook command

### ISSUE THREAD

**Issue by rembo613** [MohamadZeina/Disco_Diffusion_Local#24]
Hi there im fairly new to all this, but I have set up everything according to the tutorial sheet but, when I run the jupyter notebook command which is shown in detail in the image I have attached, an error message pops up. Is there a way to fix this file error?
![Capture](https://user-images.githubusercontent.com/106804904/171856352-b4d87897-2774-429a-a148-c51aa9cc40a1.PNG)
 
Furthermore, when running the cells, does anyone mind explaining the process a bit more in-depth if possible. I understand I can change all my setting but how does rendering work when you run it? and when you do run the cells do you have to reach step 5 before Ubuntu does anything? 

Also is there anyway to see your processed images like in the original disco diffusion in like 50 step gaps or do you have to wait until the render is complete?

ONTOP of all that now im getting alot of ERROR 404 HTTP request sent, awaiting response... 404 not found messages. Any fixes?

Thanks, sorry for the lot of questions!

**Comment by Kallamamran** [comment]
I have the same red text :(

**Comment by MohamadZeina** [comment]
If jupyter runs, you can ignore the red text. Closing this as it was posted a while ago - if still experiencing issues please open again, but stick to 1 problem per issue.
