### ISSUE TITLE
Nvidia required as a channel on Anaconda Install

### ISSUE THREAD

**Issue by jakeblakeley** [MohamadZeina/Disco_Diffusion_Local#26]
I needed to include -c nvidia to properly install cudetoolkit. May be good to update. Full command:

> conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia -c conda-forge

**Comment by MohamadZeina** [comment]
This depends on a lot of things like OS, pytorch version, cudatoolkit version. Will keep the instructions that got it to work on windows (and Linux users likely know how to troubleshoot lol).
