### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)

### ISSUE THREAD

**Issue by maxfomitchev2** [MohamadZeina/Disco_Diffusion_Local#27]
I am able to run the notebook, but get the following error. How do I fix it?

Looking in links: https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu111_pyt1100/download.html
ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)
ERROR: No matching distribution found for pytorch3d

**Comment by SunburstPC** [comment]
Managed to solve the issue with this post https://www.reddit.com/r/DiscoDiffusion/comments/tv44y2/error_no_module_named_py3d_tools/

But then I ran into another issue which I have not fixed yet when running the model:

"EOFError: Ran out of input" will make a separate post for this.

If the solution above fixes the pytorch problem and lets you run everything with no problem update me on that, might have screwed something up on my setup.

**Comment by MohamadZeina** [comment]
Thanks
