### ISSUE TITLE
Weird spinning structure render result after initial frame.

### ISSUE THREAD

**Issue by SunburstPC** [MohamadZeina/Disco_Diffusion_Local#29]
I finally got DD to work locally but one last issue I have is that the output after the initial frame turns into a "+" sign like rotating structure that lacks any detail trying to be rendered.

The initial frame rendered looks great but once it starts being as a starting point for the next frames it looks like in this video:

https://gfycat.com/delectablemasculineimperialeagle

-Disabling the second model does not fix the issue.

-Removing translation parameters did not fix the issue.

**Comment by MohamadZeina** [comment]
Try removing all movement - 3D and 2D, translation but also rotation. Reopen if not fixed
