### ISSUE TITLE
CUDA kernel errors might be asynchronously reported at some other API call

### ISSUE THREAD

**Issue by fabmeyer** [MohamadZeina/Disco_Diffusion_Local#3]
`RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
`

When running 4. Diffuse!
Any thoughts?

**Comment by MohamadZeina** [comment]
Can you please provide:
OS
PyTorch version 
Cuda toolkit version, and how was this installed (as I recommend in the README or another way?)
GPU make and RAM 
Do you have any other GPU applications running? 

I've had this issue if I've previously ran some tensorflow code but haven't restarted the kernel (so memory wasn't freed up), or when I tried running on my  laptop with only 4GB VRAM
