### ISSUE TITLE
Solving Environment Failed

### ISSUE THREAD

**Issue by Cyberecs** [MohamadZeina/Disco_Diffusion_Local#32]
Hello,

Everything worked okey but after I enter this command **conda install opencv -c conda-forge** I receive the following message.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

Can you please advise? 

Thank youu!

**Comment by MohamadZeina** [comment]
Weird. Looks like this isn’t a new environment though? Try in a new environment, and failing that, try installing more libraries at the same time, ie:

`conda install opencv jupyter pandas requests matplotlib -c conda-forge`
