### ISSUE TITLE
cudatoolkit 11.1 doesn't exist?

### ISSUE THREAD

**Issue by thegrandmasterflash** [MohamadZeina/Disco_Diffusion_Local#37]
On running
`conda install pytorch==1.10 torchvision torchaudio cudatoolkit==11.1 -c pytorch -c conda-forge`

I get the following error
`PackagesNotFoundError: The following packages are not available from current channels:`
`  - cudatoolkit==11.1`

In the instructions, it says "_Finding the above took a lot of trial and error. The difficulty was finding a pytorch and cudatoolkit combination which works with pytorch3d (required later). The above worked for me_."

[Looking it up](https://anaconda.org/search?q=cudatoolkit), I can't even find a cudatoolkit 11.1.  There's an 11.3 and an 11.7, neither of which seem to end up working in the notebook.  Any ideas?

**Comment by thegrandmasterflash** [comment]
I may have just found a solution.  Leaving this up for anyone else who struggles with this problem.  On [this page](https://conda.anaconda.org/conda-forge/linux-64/) it lists cudatoolkit-11.1.1 which is installing for me now.  Command:

`conda install pytorch==1.10 torchvision torchaudio cudatoolkit==11.1.1 -c pytorch -c conda-forge`

**Comment by AmberElferink** [comment]
I had an issue with that command as well, this worked for me:
`conda install pytorch==1.10 torchvision torchaudio cudatoolkit=11.1 -c pytorch -c
 conda-forge`
According to the pytorch install command on the website, the cudatoolkit version should be a single = (instead of double) and that worked for me. Same result, it also installed 11.1.1

**Comment by Kallamamran** [comment]
This worked for me. Thanks @thegrandmasterflash 

conda install pytorch==1.10 torchvision torchaudio cudatoolkit==**11.1.1** -c pytorch -c conda-forge

**Comment by MohamadZeina** [comment]
Thanks all

**Comment by hellosteadman** [comment]
Not working any more, sadly. Looks like cudatoolkit has been taken down.

**Comment by rushrukh** [comment]
Not working anymore. Both - 

`conda install pytorch==1.10 torchvision torchaudio cudatoolkit==11.1.1 -c pytorch -c conda-forge`  and
`conda install pytorch==1.10 torchvision torchaudio cudatoolkit=11.1.1 -c pytorch -c conda-forge`

**Comment by floschne** [comment]
For me, it's also not working with other `cudatoolkit` versions and it's actually a bit weird:
As one can simply look up, the package does exist, e.g., here https://anaconda.org/nvidia/cudatoolkit or here https://anaconda.org/conda-forge/cudatoolkit
However, I get an error that it cannot be found (no matter what version) when I run `conda install`. Also when searching it via  `conda search`
```bash
❯ conda search -f cudatoolkit -c nvidia   --override-channels
Loading channels: done
No match found for: cudatoolkit. Search: *cudatoolkit*

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit

Current channels:

  - https://conda.anaconda.org/nvidia/osx-64
  - https://conda.anaconda.org/nvidia/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

or it only finds older `dev`-versions

```bash
❯ conda search -f cudatoolkit -c conda-forge   --override-channels
Loading channels: done
No match found for: cudatoolkit. Search: *cudatoolkit*
# Name                       Version           Build  Channel
cudatoolkit-dev                  9.2          py36_2  conda-forge
cudatoolkit-dev                  9.2          py37_0  conda-forge
cudatoolkit-dev                 10.0               1  conda-forge
cudatoolkit-dev                 10.0               2  conda-forge
cudatoolkit-dev                 10.0          py36_0  conda-forge
cudatoolkit-dev             10.1.243      h0b31af3_1  conda-forge
cudatoolkit-dev             10.1.243      h0b31af3_2  conda-forge
cudatoolkit-dev             10.1.243      h0b31af3_3  conda-forge
cudatoolkit-dev             10.1.243      h1de35cc_0  conda-forge
```

Has anyone an idea why this happens?

**Comment by thegrandmasterflash** [comment]
I can't help with that, but I can say that if you're trying to get DiscoDiffusion running locally, the easiest way is to install "Visions Of Chaos".  It's a free windows binary that allows an easy entry with GUI to get all the different diffusion tools working easily.

**Comment by alpakbaci** [comment]
`conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia -c conda-forge` this was worked for me but installing 11.1.1 instead of 11.1? do you guys know why is that
