### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi'

### ISSUE THREAD

**Issue by Ens-Primum** [MohamadZeina/Disco_Diffusion_Local#39]
Good morning.  I'm having trouble running the notebook.  I have a feeling it is something simple but my Google-fu is not helping in this case:

![image](https://user-images.githubusercontent.com/66501392/183928349-ed20b325-9d47-436f-8c82-19c580d31b22.png)

**Comment by damien122** [comment]
hi, do you have Nvidia-smi installed?
Just try in a new line:
`!nvidia-smi`

If it is installed you should see a table with your Grafik card information. 

May be this would be helpful 

https://www.cyberciti.biz/faq/ubuntu-linux-install-nvidia-driver-latest-proprietary-driver/

**Comment by Ens-Primum** [comment]
BLUF: Going to look over the install directions and see if I missed anything.

`!nvidia-smi`
returns:
`-bash: !nvidia: event not found`

Followed the link and ran:
`sudo apt install nvidia-driver-510 nvidia-dkms-510`

Failed but suggested I run `apt-get update`
`apt-get update` failed due to permissions.

I used this [article](https://askubuntu.com/questions/772050/reset-the-password-in-ubuntu-linux-bash-in-windows) to switch my user to the root user and retried the update, success.

Still as the root user I retried `apt install nvidia-driver-510 nvidia-dkms-510`, success
then: `hwinfo --gfxcard --short`, failed, had to install it too with `apt-get hwinfo`.
retrying **`hwinfo --gfxcard --short` works now but returns no output.**

moved back into the notebook by running:
`conda activate pytorch_110`
and then:
`jupyter notebook --no-browser`

nvidia-smi is found now but gives a new error:
"NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."

Possible [explanation](https://askubuntu.com/questions/1175113/accessing-graphics-in-ubuntu-which-is-installed-as-an-app-in-windows-10-hp):
"I have no solid evidence to base this on, but it's possible that WSL does not actually expose all of the hardware claimed by the Host to the WSL Ubuntu environment. This may be why you can't work with it, because you don't have direct PCI access like you would in an Ubuntu installation directly on-system, but are instead basically 'containerized' within Windows. The underlying WSL abstraction library for syscalls also may not be permitted to have that access either."



Specs:
Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz   3.70 GHz
32.0 GB (RAM)
Windows 10 Pro 21H2
NVIDIA GeForce RTX 3090

**Comment by Ens-Primum** [comment]
Looks like I went after WSL/Ubuntu from the wrong direction.  I already had it installed from an earlier docker desktop installation.  Tearing that down and trying over.

**Comment by Ens-Primum** [comment]
I have completely removed Ubuntu/WSL and started over.  
`nvidia-smi` works now: 
![image](https://user-images.githubusercontent.com/66501392/184284334-e3a6e0f5-1830-4a41-9538-b337887efc37.png)

Unfortunately I'm running into a new issue:

> RuntimeError: CUDA error: no kernel image is available for execution on the device
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.


![image](https://user-images.githubusercontent.com/66501392/184284403-20adfd20-dd31-42f3-929d-d5ffc38abd21.png)

**Comment by Ens-Primum** [comment]
Error persists with different drivers:
![image](https://user-images.githubusercontent.com/66501392/184286096-3b39a17d-2023-4c2c-bf27-4d2b013de523.png)

**Comment by Ens-Primum** [comment]
Making a new post since this one was solved by me uninstalling/reinstalling WSL.
