### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by rasooul** [MohamadZeina/Disco_Diffusion_Local#4]
First of all Thank you so much for clear instructions.

However I have this issue!
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

- I followed the provided instructions.
- It is updated windows 10 
- NVIDIA GeForce RTX 3080 (UUID: GPU-92f60414-8b1f-9d4c-64a9-b3d4149e2665) 
- 64G memory
- No other application running
- Fresh reboot

Error starts like this:

Starting Run: TimeToDiscoTurbo3(0) at frame 0
Prepping model...
./model/512x512_diffusion_uncond_finetune_008100.pt
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [19], in <cell line: 153>()
    151 print(diffusion_model_path)
    152 model.load_state_dict(torch.load(diffusion_model_path, map_location='cpu'))
--> 153 model.requires_grad_(False).eval().to(device)
    154 for name, param in model.named_parameters():
    155     if 'qkv' in name or 'norm' in name or 'proj' in name:

**Comment by rasooul** [comment]
Do I have to install Visual Studio, CUDA developer ...?
It was not in the requirement!

**Comment by MohamadZeina** [comment]
Hey thanks for the detailed issue.

Which 3080 - 10GB or 12GB?

I’ve only ever gotten this error when there have been memory issues. In 2. Diffusion and CLIP model settings, try disabling all models except for 1 (and keep “use secondary model”), switch to “256x256_diffusion_uncond”. Then in settings reduce the resolution drastically (to 128x128) and see if that helps. If it works, slowly add back models and increase resolution until you find out where the limit is. 

I don’t suspect it’s to do with visual studio, as colab doesn’t have this to the best of my understanding. Will you let me know if this works so others can learn in the future?

**Comment by rasooul** [comment]
Thanks for looking into this.
3080 10GB
I made the changes and now it stopped at this error:
FileNotFoundError: [Errno 2] No such file or directory: './model/256x256_diffusion_uncond_finetune_008100.pt'

**Comment by rasooul** [comment]
my bad, it works
I changed it to “256x256_diffusion_uncond”
Thank you so much Mohamad

**Comment by MohamadZeina** [comment]
No problem, thanks for letting me know this worked. Will make a FAQ about this.
