### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace' on torch.version.cuda.replace

### ISSUE THREAD

**Issue by jamiethemorris** [MohamadZeina/Disco_Diffusion_Local#42]
![image](https://user-images.githubusercontent.com/6130489/187586751-51f2f65e-f43c-4e71-bb9f-bdf2861e7216.png)

**Comment by j3lmer** [comment]
Any updates?

**Comment by dibbl3** [comment]
Thank you for your work on this. I am completely new to Linux, Anaconda, Jupyter and Disco Diffusion so the learning curve is fun! I have the same error. Any suggestions? Also, I was expecting to see the same non-code interface for Disco Diffusion that I have used on Google Collab. Probably my naivety. Is there a way that you know of for me to change Diffusion settings without scouring the code? Again, thank you for your attention....

**Comment by MohamadZeina** [comment]
Looks like your pytorch installations aren’t succesfully seeing your GPU, you can check this by looking at the output of the following, which is already in the notebook.

`print('Using device:', DEVICE) `

This should say “cuda”, and if not, means it’s using CPU which isn’t supported.

If this is the case, the things you want to google / troubleshoot are ie “pytorch doesn’t see GPU”.
