### ISSUE TITLE
do it work with radeon hardware?

### ISSUE THREAD

**Issue by Hamdan85** [MohamadZeina/Disco_Diffusion_Local#5]
Im trying to use it locally by following your guide but I receive this: 
![image](https://user-images.githubusercontent.com/1886026/163060265-b8d26160-a715-43c0-acc3-cfca6d0a0f8e.png)

then, nothing works after this point:
![image](https://user-images.githubusercontent.com/1886026/163060495-f740ca4e-2711-4bb0-8e7f-194d617c99f6.png)

does it work with Radeon software? Is there any work around this issues?

**Comment by MohamadZeina** [comment]
Unfortunately it doesn’t work with AMD GPUs at present - only NVidia
