### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by echterosandorenmonst** [MohamadZeina/Disco_Diffusion_Local#6]
Everything went smooth till this appeared after I run "Install and import dependencies"

**Comment by MohamadZeina** [comment]
You probably forgot to install opencv - in your terminal run:

> conda` install opencv -c conda-forge

And let me know if that fixes it for you

**Comment by MohamadZeina** [comment]
Closing as I haven't heard back

**Comment by vasilzhigilei** [comment]
I had the same issue. I had to pip install opencv instead, which fixed that particular problem.

**Comment by Lordan2000** [comment]
This solution worked for me:
`pip install opencv-python-headless`
`sudo apt-get install -y libgl1-mesa-dev`
Reference: https://stackoverflow.com/questions/63977422/error-trying-to-import-cv2opencv-python-package
