### ISSUE TITLE
error  model.convert_to_fp16()

### ISSUE THREAD

**Issue by dangma1234** [MohamadZeina/Disco_Diffusion_Local#7]
Hi, I installed this to windows 11 :)
Everything is fine. I checked twice to do not mistake.
but when I try to start run all cell, This error message is coming.
I using RTX3090. I resized image size to 128 x 128, and disable all models, but it still doesn't work :)

---------------------------------------------

Starting Run: TimeToDisco(0) at frame 0
Prepping model...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_1480/836853634.py in <module>
    166         param.requires_grad_()
    167 if model_config['use_fp16']:
--> 168     model.convert_to_fp16()
    169 
    170 gc.collect()

~/disco/guided-diffusion/guided_diffusion/unet.py in convert_to_fp16(self)
    620         Convert the torso of the model to float16.
    621         """
--> 622         self.input_blocks.apply(convert_module_to_f16)
    623         self.middle_block.apply(convert_module_to_f16)
    624         self.output_blocks.apply(convert_module_to_f16)

~/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py in apply(self, fn)
    665         """
    666         for module in self.children():
--> 667             module.apply(fn)
    668         fn(self)
    669         return self

~/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py in apply(self, fn)
    665         """
    666         for module in self.children():
--> 667             module.apply(fn)
    668         fn(self)
    669         return self

~/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py in apply(self, fn)
    666         for module in self.children():
    667             module.apply(fn)
--> 668         fn(self)
    669         return self
    670 

~/disco/guided-diffusion/guided_diffusion/fp16_util.py in convert_module_to_f16(l)
     18     """
     19     if isinstance(l, (nn.Conv1d, nn.Conv2d, nn.Conv3d)):
---> 20         l.weight.data = l.weight.data.half()
     21         if l.bias is not None:
     22             l.bias.data = l.bias.data.half()

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by MohamadZeina** [comment]
Hey, thanks for the thorough issue. Do you mean you disabled all models except for 1, or disabled all of them? You need 1 model for things to work.

I've not run into this before though. It doesn't look like a memory issue - your 3090 shouldn't struggle with 128x128. 

What do you get if you run the following in a cell in the same notebook?

```
import torch
print(torch.cuda.is_available())
```

**Comment by MohamadZeina** [comment]
Closing this because I haven't heard back

**Comment by saruzaru** [comment]
Hi, i'm having issues with this at the moment, is there a fix for this?
I tried the "import torch
print(torch.cuda.is_available())" 
and the response is True.
