### ISSUE TITLE
NameError: name 'model_config' is not defined

### ISSUE THREAD

**Issue by dada78** [MohamadZeina/Disco_Diffusion_Local#8]
HI guys,
I am running v5 in the browser and was wondering how to fix this error? I was running the process and a beautiful picture appeared and then I wake up to this with no picture saved. I am running ColabPro. Thanks!

`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-4-ca6ef62fa68a>](https://localhost:8080/#) in <module>()
     40 timestep_respacing = f'ddim{steps}'
     41 diffusion_steps = (1000//steps)*steps if steps < 1000 else steps
---> 42 model_config.update({
     43     'timestep_respacing': timestep_respacing,
     44     'diffusion_steps': diffusion_steps,

NameError: name 'model_config' is not defined`

**Comment by MohamadZeina** [comment]
Hey, this repo is for my local port of Disco Diffusion, issues with the colab are best handled by the people who made it. 

That said, you could be getting disconnected. Colab Pro Plus has background execution but normal Pro will cut you off after inactivity. Some searching will show you ways around this, but I've never used these.

Closing this issue as not relevant though.
