### ISSUE TITLE
No Write Permissions

### ISSUE THREAD

**Issue by cambarnes7** [MohamadZeina/Disco_Diffusion_Local#9]
After opening jupyter notebook and using either the included v5 or the most recent v5.2 .ipynb file, running some of the cells results in an error due to not having the permissions to write files.  Jupyter still seems to be able to read files, as I can manually create folders and Jupyter will be able to read them, but it's unable to write folders or files to those folders.

**Comment by MohamadZeina** [comment]
What is the exact error message you’re getting?

**Comment by MohamadZeina** [comment]
Did you manage to get to the bottom of this? You say no output in the terminal - but is the notebook running as expected?

**Comment by cambarnes7** [comment]
I actually ended up using a different tutorial which uses VS instead of Jupyter which worked flawlessly without any errors.  Since then I have reinstalled Windows so I probably cannot recreate this issue anymore.  The first few cells did run with no errors but when it needed to write any files / folders, the cell output usually gave an error and the terminal would have many messages saying it failed to write to those files / folders, stating it had no permissions to do so.

**Comment by TotallyNotChina** [comment]
> I actually ended up using a different tutorial which uses VS instead of Jupyter which worked flawlessly without any errors. Since then I have reinstalled Windows so I probably cannot recreate this issue anymore. The first few cells did run with no errors but when it needed to write any files / folders, the cell output usually gave an error and the terminal would have many messages saying it failed to write to those files / folders, stating it had no permissions to do so.

what tutorial did you use to do this with VS?

**Comment by bk977113** [comment]
> I ran into the same issue. I had unpacked the downloaded zip file in windows. This saved the files as root, not as the user I entered on creation of Ubuntu. Deleting the folder and unzipping within Ubuntu solved the issue for me.

Can you give a step by step on how you did this?

**Comment by HolgerFoerterer** [comment]
> Can you give a step by step on how you did this?
 
I rebooted and logged in using the WSL credentials, then deleted the already unpacked DiscoDiffusion folder by typing

`sudo rm -rf Disco_Diffusion_Local-main`

at the command prompt. After this, I installed unzip with

`sudo apt install unzip`

and used the now available unzip command to unpack the zip again:

`unzip Disco_Diffusion_Local-main.zip`

This will create a new _Disco_Diffusion_Local-main_ subfolder that you should have write access to. You can verify that the user is no longer root but the user you defined on the creation of the WSL environment by using `ls -al`.

**Comment by bk977113** [comment]
> > Can you give a step by step on how you did this?
> 
> I rebooted and logged in using the WSL credentials, then deleted the already unpacked DiscoDiffusion folder by typing
> 
> `sudo rm -rf Disco_Diffusion_Local-main`
> 
> at the command prompt. After this, I installed unzip with
> 
> `sudo apt install unzip`
> 
> and used the now available unzip command to unpack the zip again:
> 
> `unzip Disco_Diffusion_Local-main.zip`
> 
> This will create a new _Disco_Diffusion_Local-main_ subfolder that you should have write access to. You can verify that the user is no longer root but the user you defined on the creation of the WSL environment by using `ls -al`.

Thank you. This fixed it.
